"""Add content related tables

Revision ID: bd152e2f5817
Revises: 
Create Date: 2025-03-27 16:11:12.173723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd152e2f5817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=False),
    sa.Column('visual_affinity', sa.Float(), nullable=True),
    sa.Column('auditory_affinity', sa.Float(), nullable=True),
    sa.Column('kinesthetic_affinity', sa.Float(), nullable=True),
    sa.Column('reading_affinity', sa.Float(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_contents_id'), 'learning_contents', ['id'], unique=False)
    op.create_table('learning_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_learning_tags_id'), 'learning_tags', ['id'], unique=False)
    op.create_table('content_tag_associations',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_contents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['learning_tags.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_table('user_content_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('difficulty_feedback', sa.Integer(), nullable=True),
    sa.Column('relevance_feedback', sa.Integer(), nullable=True),
    sa.Column('engagement_feedback', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['learning_contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_content_interactions_id'), 'user_content_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_content_interactions_id'), table_name='user_content_interactions')
    op.drop_table('user_content_interactions')
    op.drop_table('content_tag_associations')
    op.drop_index(op.f('ix_learning_tags_id'), table_name='learning_tags')
    op.drop_table('learning_tags')
    op.drop_index(op.f('ix_learning_contents_id'), table_name='learning_contents')
    op.drop_table('learning_contents')
    # ### end Alembic commands ###
